#!/bin/bash

set -eu

cd "$(dirname "$0")/.."

if ! cf curl /v2/info | grep -F 'london.cloud.service.gov.uk' &> /dev/null; then
  >&2 echo "It looks like you're not targetting the london region"
  >&2 echo "  cf login -a api.london.cloud.service.gov.uk --sso"
  exit 1
fi

cf t -o govuk-paas -s learn-to-code
cf v3-create-app learn-to-code
cf v3-apply-manifest -f manifest.yml
cf v3-zdt-push learn-to-code -p build --wait-for-deploy-complete

(
cd "examples/lesson-1-html-and-css/"
cf v3-create-app apply-for-a-barking-permit
cf v3-apply-manifest -f manifest.yml
cf v3-zdt-push apply-for-a-barking-permit --wait-for-deploy-complete
)
