name: Continuous Delivery

on:
  workflow_dispatch: {}
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1 # version read from `.ruby-version` file
      with:
        bundler-cache: true

    - name: Build
      run: |
        bundle install
        bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
